services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: products-api-app
    volumes:
      - ./products-api:/var/www/html
      - ./products-api/storage:/var/www/html/storage
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      APP_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: products-api-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: products-api-nginx
    ports:
      - "8000:80"
    volumes:
      - ./products-api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  vue-dev:
    build:
      context: .
      dockerfile: docker/vue/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

volumes:
  mysql_data:

networks:
  app-network: