services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: products-api-app
    ports:
      - "8001:80"
    depends_on:
      - mysql
    environment:
      APP_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret

  mysql:
    image: mysql:8
    container_name: products-api-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: products-api-nginx
    ports:
      - "8000:80"
    volumes:
      - ./products-api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql_data:
