# Build stage
FROM node:20 AS build-stage

WORKDIR /app
COPY ./frontend .

RUN npm install
RUN npm run build

# Production stage
FROM nginx:alpine AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./docker/nginx/prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
